### ISSUE TITLE
libgfapi + qemu in Ubuntu 16.04?

### ISSUE THREAD

**Issue by howels** [monotek/GlusterFS-launchpad_buildscripts#1]
What's the status of the libgfapi + qemu in Ubuntu 16.04 and newer releases? I've had problems with Gluster 3.7 using your PPA on 16.04 whereas 14.04 worked, as you have found yourself but the exact cause was never located. 

Would be great to leverage the gluster block provider again instead of FUSE!

Thanks for any guidance you can supply.

**Comment by monotek** [comment]
Sorry, but i can't tell. 
I don't use ubuntu & glusterfs anymore in my current job.
Maybe the Glusterfs guys can help @ https://bugzilla.redhat.com/show_bug.cgi?id=1398839
